### ISSUE TITLE
not compatible with WP 4.2.x

### ISSUE THREAD

**Issue by senlin** [senlin/so-pinyin-slugs#2]
Just found out that the plugin is in fact not compatible with WP 4.2 and up.

The cause most likely is the way that WP now accepts Asian characters, which basically destroys the permalink rewrite rules we use with the plugin.

We are looking for a way to make the plugin work again, in the meantime thanks for your patience.

**Comment by senlin** [comment]
actually turns out to be a non-issue...

**Comment by cattagnia** [comment]
Good Morning, You have some news of compatibility with WP 4.2?

Thank's for all.
Best Regards

**Comment by senlin** [comment]
The fact that this issue is in fact **closed** AND the comment that clearly says that this *actually turns out to be a non-issue...* should speak for itself, no?
