### ISSUE TITLE
add "-" between pinyin of each character 

### ISSUE THREAD

**Issue by suncrimson** [senlin/so-pinyin-slugs#3]
Hi Piet

Great work and thanks so much for this little plug and it makes my life so much easier.

I just have a small request and I am wondering if here is right place to raise it.

Is that possible to add "-" between pinyin of each character? It would make the url much easier to read and understand.

Thanks
Alex

**Comment by senlin** [comment]
Hi Alex, thanks for the kind words, glad to hear that the plugin is useful for you. Also saw the review over at the WP Plugins Directory, thanks :)

I guess it would be technically possible to add a dash between each character, but that would only improve readability for some humans. 

Chinese search engines are used to reading pinyin without dashes. I haven't tested it, but my guess would be that dashed would confuse search engines. Also people communicating in pinyin don't use dashes. 

On top of that I think that people who are used to pinyin hardly have any trouble understanding where a character stops and a new one begins. 

Do you have any indication that dashes are in fact used anywhere?

Thanks,
Piet

**Comment by suncrimson** [comment]
Hi Piet

Thanks for the prompt reply. : )

No, thats just my personal preference. For long sentence, the dash would
make the url easier to read, at least for me.

Never mind, if there is benefit from SEO perspective then I am definitely
fine with it.

Interestingly I found Baidu can recognise the input with "-" or "|" , see
below:
[image: Inline image 1]

But I dont know if this related to SEO.

Thank you very much for your time and effort!

Alex



On Thu, Dec 3, 2015 at 9:32 PM, Piet Bos <notifications@github.com> wrote:

> Hi Alex, thanks for the kind words, glad to hear that the plugin is useful
> for you. Also saw the review over at the WP Plugins Directory, thanks :)
>
> I guess it would be technically possible to add a dash between each
> character, but that would only improve readability for some humans.
>
> Chinese search engines are used to reading pinyin without dashes. I
> haven't tested it, but my guess would be that dashed would confuse search
> engines. Also people communicating in pinyin don't use dashes.
>
> On top of that I think that people who are used to pinyin hardly have any
> trouble understanding where a character stops and a new one begins.
>
> Do you have any indication that dashes are in fact used anywhere?
>
> Thanks,
> Piet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/senlin/so-pinyin-slugs/issues/3#issuecomment-161589127>
> .
>



-- 
Alex Zhen
+61439199331

**Comment by senlin** [comment]
Interesting. The image didn't make it through, maybe you can post it again?
