### ISSUE TITLE
This plugin breaks JetPack related posts

### ISSUE THREAD

**Issue by physixfan** [senlin/so-pinyin-slugs#7]
When I activate this plugin, the JetPack related posts on my Chinese posts disappears. The related posts come back when I disable this plugin.

**Comment by senlin** [comment]
Perhaps you need to re-index your posts first or clear jetpack's transient or cache? 

Please read [**all documentation on the Related Posts module of the Jetpack plugin**](https://jetpack.com/support/related-posts/) carefully, then you will understand why this is not a bug and why our plugin does not break anything.

**Comment by physixfan** [comment]
I am pretty sure it's your plugin that breaks the related posts. As long as I disable your plugin, the related posts show up immediately. Actually I have contacted JetPack and they did a re-index for me, nothing changed.

**Comment by physixfan** [comment]
By the way, I think it is a conflict between your plugin and Polylang. When I enable both, the related posts are broken. When I disable either one, the related posts are back.

**Comment by senlin** [comment]
site url please

**Comment by physixfan** [comment]
https://www.uscreditcardguide.com/zh/
Thanks

**Comment by senlin** [comment]
From the site it is not visible that the SO Pinyin Slugs plugin is in fact active.

The post title 加拿大 eTA 介绍 should have a slug of jianada-eTA-jieshao or jianadaeTAjieshao, but has a slug of "canada-eta" instead.

The category 签证攻略 should have a slug of qianzhenggonglve, but has a slug of "visa" instead.

Then if you would have made the effort to have a look at the soutrce code, you would have seen that in fact the Jetpack module is loaded, but nothing shows as there simply is no matching content.

<img src="https://www.evernote.com/shard/s19/sh/6ee0d6bd-a387-447a-8c77-ecfce083b6a0/39ca44d978a68d61/res/9941e448-f91d-4002-8815-ba0388a22dc0/skitch.png" />

**Comment by physixfan** [comment]
The SO pinyin plugin is active. I slug is different than you expect because I changed the title manually and the slug for the tag existed before I installed your plugin. 

I know the JetPack module is there, but it showed nothing. Please take a look at this site: http://physixfan.staging.wpengine.com/zh/ It is an exact copy of my site, just with one difference: SP pinyin plugin is disabled.

**Comment by senlin** [comment]
Link to staging site is not relevant IMO. 

What I understand from earlier referred to Jetpack docs is:

* Related content will not appear unless [Jetpack] thinks it can show at least 3 good results
* Related content is automatically generated based on the content of the post and any tags or categories **if they exist** (emphasis mine).
* Related Posts for a given article are **cached for 12 hours** (emphasis mine).

**Comment by physixfan** [comment]
It IS relevant. I just want to show you that, as long as I disable SO pinyin, the related posts show up immediately. I can do the same on my main site, if you want.

**Comment by senlin** [comment]
The reason I say it is irrelevant, is because you are not using the SO Pinyin Slugs plugin to begin with. 

Furthermore it is easy to point to SO Pinyin Slugs as the breaker, it might as well be Jetpack and as there are not any other reports of this issue, whereas Jetpack is a fairly popular plugin, I am very hesitant to agree that SO Pinyin Slugs "breaks" Jetpack Related Posts.

**Comment by physixfan** [comment]
Note that on my staging site, on which SO pinyin is disabled, the related posts are showing. While on my main site, with SO pinyin is enabled, the related posts are broken. Perhaps I failed to make it clear previously.

**Comment by physixfan** [comment]
This problem shows only when both SO pinyin slug AND Polylang are activated. So I assume this is still a conflict with Polylang.

**Comment by senlin** [comment]
Although SO Pinyin Slugs has been installed, you are not using it as such and therefore I must conclude that this indeed seems to be a conflict with the Polylang plugin. Note also that with WPML there is no issue whatsoever.

I don't like to play the "point fingers game", but in this case I'm afraid that it is the Polylang plugin causing the issue(s) not the SO Pinyin Slugs plugin...

**Comment by physixfan** [comment]
OK. I'll contact Polylang about this.

**Comment by physixfan** [comment]
A fix is suggested by the author of Polylang Pro. I'll just paste it here so that if somebody has the same problem can Google the solution:

Frédéric replied
Mar 6, 19:12
Hi,

It is indeed likely that there is conflict when all 3 plugins are activated. I explain:

Polylang tells Jetpack related posts to make sure that all related posts are in the same language. Otherwise depending on the languages used, there is a risk that related posts mix languages. The Jetpack server uses a sanitized language name. Thus Polylang communicates with the Jetpack server with a sanitized language name too. The issue is that SO Pinyin Slug modifies the sanitization function. The plugin being active on your server but not on the Jetpack server, the sanitized language name is no more the same on both servers and the communication between the Jetpack server and Polylang is broken.

You can remove the Polylang filter by adding these lines in the functions.php of your child theme.

if ( class_exists( 'PLL_Plugins_Compat' ) ) {
remove_filter( 'jetpack_relatedposts_filter_filters', array( PLL_Plugins_Compat::instance(), 'jetpack_relatedposts_filter_filters' ), 10, 2 );
}

That way Polylang won't filter the related posts anymore but that should not be an issue as I don't see a risk that the Jetpack server mixes English and Chinese.

**Comment by senlin** [comment]
Glad to hear that Frédéric came with a solution!
