### ISSUE TITLE
How to use this plugin in my theme or plugin ?

### ISSUE THREAD

**Issue by chrisgan33** [senlin/so-pinyin-slugs#8]
Hello , Is there some PHP functions or shortcode to use in highly custom way ?

Case , with  wp_insert_term  :
```
array{
slug = 'so-pinyin-slugs(...)';
}
```

THX

**Comment by senlin** [comment]
Sorry, I have no idea what you're talking about.
What exactly are you trying to accomplish?

**Comment by chrisgan33** [comment]
With this plugin,
I want use a function to make "中文" to "zhongwen", 

in my theme or plugin, 
<?php
echo so-pinyin-slugs("中文");  // print  zhongwen
?>

Does a function exist to make this in this plugin ?

**Comment by senlin** [comment]
That is exactly what the plugin already does for permalinks.
Where do you want/need to change it?

**Comment by chrisgan33** [comment]
not change, just to use like this 

`    $term_name = '中文';
    $taxonomy = 'class';
    
    $result = wp_insert_term(
      $term_name, // the term 
      $taxonomy, // the taxonomy
      array(
        'description'=> 'A category named in chinese.',
        'slug' => your_plugin_offered_function_name($term_name),
        'parent'=> 0
      )
    );`

**Comment by senlin** [comment]
The slugs (everything displayed in permalinks) already changes on a Chinese language site.

Descriptions can be edited by the user, so if you want to write 中文 there and "transform" it into pinyin, then that is already possible and not something the plugin will and can do for you.

If you want the plugin to do anything else it already does, feel free to contribute.
